### ISSUE TITLE
Build error Failed to find XercesC (missing: XercesC_LIBRARY XercesC_INCLUDE_DIR XercesC_VERSION)

### ISSUE THREAD

**Issue by skuti-is** [BelledonneCommunications/linphone-desktop#216]
Unable to build on Ubuntu 18.04 amd64
$ make
...
[ 84%] Creating directories for 'EP_linphone'
[ 85%] No download step for 'EP_linphone'
[ 86%] No patch step for 'EP_linphone'
[ 86%] No update step for 'EP_linphone'
[ 86%] Performing configure step for 'EP_linphone'
loading initial cache file /root/git/linphone-desktop/WORK/desktop//tmp/EP_linphone/EP_linphone-cache-Release.cmake
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found XML2: /usr/include/libxml2  
-- Failed to find XercesC (missing: XercesC_LIBRARY XercesC_INCLUDE_DIR XercesC_VERSION) 
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibXsd (missing: LIBXSD_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibXsd.cmake:43 (find_package_handle_standard_args)
  CMakeLists.txt:137 (find_package)

-- Configuring incomplete, errors occurred!
See also "/root/git/linphone-desktop/WORK/desktop/Build/linphone/CMakeFiles/CMakeOutput.log".
CMakeFiles/EP_linphone.dir/build.make:114: recipe for target '/root/git/linphone-desktop/WORK/desktop/Stamp/EP_linphone/EP_linphone-configure' failed
make[3]: *** [/root/git/linphone-desktop/WORK/desktop/Stamp/EP_linphone/EP_linphone-configure] Error 1
make[3]: Leaving directory '/root/git/linphone-desktop/WORK/desktop/cmake'
CMakeFiles/Makefile2:188: recipe for target 'CMakeFiles/EP_linphone.dir/all' failed
make[2]: *** [CMakeFiles/EP_linphone.dir/all] Error 2
make[2]: Leaving directory '/root/git/linphone-desktop/WORK/desktop/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/git/linphone-desktop/WORK/desktop/cmake'
Makefile:14: recipe for target 'desktop-build' failed
make: *** [desktop-build] Error 2

**Comment by Wescoeur** [comment]
Have you tried to rebuild with: 
```
git submodule sync && git submodule update --init --recursive
./prepare.py -c
./prepare.py
```
XercesC is a new dependency and maybe your source files are not correctly updated.

**Comment by skuti-is** [comment]
found the missing package, fixed with:
# apt install libxerces-c-dev

**Comment by ibraheemalkilanny** [comment]
@skuti-is No still getting the same error after installing that

```
-- Found XercesC: /usr/lib/x86_64-linux-gnu/libxerces-c.so (found version "3.2.0")
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibXsd (missing: LIBXSD_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibXsd.cmake:48 (find_package_handle_standard_args)
  CMakeLists.txt:129 (find_package)


-- Configuring incomplete, errors occurred!
See also "/root/flexisip/WORK/flexisip/Build/linphone/CMakeFiles/CMakeOutput.log".
CMakeFiles/EP_linphone.dir/build.make:116: recipe for target '/root/flexisip/WORK/flexisip/Stamp/EP_linphone/EP_linphone-configure' failed
make[3]: *** [/root/flexisip/WORK/flexisip/Stamp/EP_linphone/EP_linphone-configure] Error 1
make[3]: Leaving directory '/root/flexisip/WORK/flexisip/cmake'
CMakeFiles/Makefile2:120: recipe for target 'CMakeFiles/EP_linphone.dir/all' failed
make[2]: *** [CMakeFiles/EP_linphone.dir/all] Error 2
make[2]: Leaving directory '/root/flexisip/WORK/flexisip/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/flexisip/WORK/flexisip/cmake'
Makefile:14: recipe for target 'flexisip-build' failed
make: *** [flexisip-build] Error 2
```
From your code at https://gitlab.linphone.org/BC/public/liblinphone/blob/master/cmake/FindLibXsd.cmake#L33
we can see that you try to find a path 
`xsd/cxx/config.hxx`
but this file does not exist in that library, even if you download sources from http://xerces.apache.org/xerces-c/download.cgi

**Comment by julonexus** [comment]
@ibraheemalkilanny Xsd should be at version 4. There are building issues with other versions.
Thanks for pointing this path, it may help to resolve this kind of issue.
