### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by gcd445** [BelledonneCommunications/linphone-desktop#24]
Im building linphone-desktop , followed the instructions in readme
using cmake 3.8.1
python prepare.py created the solution file , build it

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol _mbedtls_snprintf [C:\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\linphone-desktop\WORK\desktop\cmake\x509_crt.obj	1	
Error	LNK2001	unresolved external symbol _mbedtls_snprintf [C:\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\linphone-desktop\WORK\desktop\cmake\x509_crl.obj	1	
Error	LNK2001	unresolved external symbol _mbedtls_snprintf [C:\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\linphone-desktop\WORK\desktop\cmake\x509_crt.obj	1	
Error	LNK2001	unresolved external symbol _mbedtls_snprintf [C:\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\linphone-desktop\WORK\desktop\cmake\x509_csr.obj	1	
Error	LNK2001	unresolved external symbol _mbedtls_snprintf [C:\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\linphone-desktop\WORK\desktop\cmake\x509_crl.obj	1	
Error	LNK2001	unresolved external symbol _mbedtls_snprintf [C:\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\linphone-desktop\WORK\desktop\cmake\x509_csr.obj	1	
Error	LNK2019	unresolved external symbol _mbedtls_snprintf referenced in function _mbedtls_x509_dn_gets [C:\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\linphone-desktop\WORK\desktop\cmake\x509.obj	1	
Error	LNK2019	unresolved external symbol _mbedtls_snprintf referenced in function _mbedtls_x509_dn_gets [C:\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\linphone-desktop\WORK\desktop\cmake\x509.obj	1	
Error	LNK1120	1 unresolved externals [C:\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\linphone-desktop\WORK\desktop\Build\mbedtls\library\MinSizeRel\mbedx509.dll	1	
Error	LNK1120	1 unresolved externals [C:\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\linphone-desktop\WORK\desktop\Build\mbedtls\library\MinSizeRel\mbedx509.dll	1	
Error	MSB6006	"cmd.exe" exited with code 2.	EP_ffmpeg	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	
Error	MSB6006	"cmd.exe" exited with code 1.	EP_bctoolbox	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	
Error	MSB6006	"cmd.exe" exited with code 1.	EP_belr	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	
Error	MSB6006	"cmd.exe" exited with code 1.	EP_bzrtp	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	
Error	MSB6006	"cmd.exe" exited with code 1.	EP_ortp	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	
Error	MSB6006	"cmd.exe" exited with code 1.	EP_bellesip	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	
Error	MSB6006	"cmd.exe" exited with code 1.	EP_belcard	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	
Error	MSB6006	"cmd.exe" exited with code 1.	EP_ms2	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	
Error	MSB6006	"cmd.exe" exited with code 1.	EP_linphone	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	

```

**Comment by velichkov** [comment]
The `_mbedtls_snprintf` has been fixed, you need to update the `mbedtls` library.

```
cd submodules/externals/mbedtls/
git fetch
git checkout -b linphone origin/linphone
```

**Comment by afe39** [comment]
Still having this error.
Last commit cloned is:

commit c49ec0f13bb57da390a7cbd186fc5caf97431543
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Tue Jun 13 15:46:14 2017 +0200

    Fix windows compilation of mbedtls

**Comment by RealDigitApps** [comment]
Eperience the problem, please advice

![default](https://user-images.githubusercontent.com/25883834/27802046-09a80558-602a-11e7-9dc8-a95dfd7c52e3.png)

**Comment by chowdarynamala** [comment]
Any update on this issue fix? I am also facing the same set of errors when I try to build even after doing the 
git checkout -b linphone origin/linphone

**Comment by mossabkhabbaz** [comment]
Same Errors, after try
```
cd submodules/externals/mbedtls/
git fetch
git checkout -b linphone origin/linphone
```
and after python prepare.py and build it, please advice

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol _mbedtls_snprintf [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\Users\12\Desktop\linphone-desktop\WORK\desktop\cmake\x509_csr.obj	1	
Error	LNK2019	unresolved external symbol _mbedtls_snprintf referenced in function _mbedtls_x509_dn_gets [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\Users\12\Desktop\linphone-desktop\WORK\desktop\cmake\x509.obj	1	
Error	LNK2001	unresolved external symbol _mbedtls_snprintf [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\Users\12\Desktop\linphone-desktop\WORK\desktop\cmake\x509_crl.obj	1	
Error	LNK2001	unresolved external symbol _mbedtls_snprintf [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\Users\12\Desktop\linphone-desktop\WORK\desktop\cmake\x509_crt.obj	1	
Error	LNK1120	1 unresolved externals [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\mbedtls\library\Debug\mbedx509.dll	1	
Error	LNK2019	unresolved external symbol _mbedtls_snprintf referenced in function _mbedtls_x509_dn_gets [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\Users\12\Desktop\linphone-desktop\WORK\desktop\cmake\x509.obj	1	
Error	LNK2001	unresolved external symbol _mbedtls_snprintf [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\Users\12\Desktop\linphone-desktop\WORK\desktop\cmake\x509_crl.obj	1	
Error	LNK2001	unresolved external symbol _mbedtls_snprintf [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\Users\12\Desktop\linphone-desktop\WORK\desktop\cmake\x509_crt.obj	1	
Error	LNK2001	unresolved external symbol _mbedtls_snprintf [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\Users\12\Desktop\linphone-desktop\WORK\desktop\cmake\x509_csr.obj	1	
Error	LNK1120	1 unresolved externals [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\mbedtls\library\mbedx509.vcxproj]	EP_mbedtls	C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\mbedtls\library\Debug\mbedx509.dll	1	

```

**Comment by chowdarynamala** [comment]
Try doing checkout 93f8cbe7bf25d50cea737194a19d0efaf9ff7081 . I also faced same issue earlier and it got resovled after taking the latest version

**Comment by mossabkhabbaz** [comment]
Thanks a lot but i faced some new error after try checkout 93f8cbe7bf25d50cea737194a19d0efaf9ff7081,
as follow error list, would you please advice

`Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6006	"cmd.exe" exited with code 2.	EP_ffmpeg	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	
Error	MSB6006	"cmd.exe" exited with code 1.	EP_libxsd	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\ortp\src\ortp.vcxproj]	EP_ortp	C:\Users\12\Desktop\linphone-desktop\submodules\ortp\src\payloadtype.c	35	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\ortp\src\ortp.vcxproj]	EP_ortp	C:\Users\12\Desktop\linphone-desktop\submodules\ortp\src\port.c	94	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\ortp\src\ortp.vcxproj]	EP_ortp	C:\Users\12\Desktop\linphone-desktop\submodules\ortp\src\rtcp.c	373	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\ortp\src\ortp.vcxproj]	EP_ortp	C:\Users\12\Desktop\linphone-desktop\submodules\ortp\src\payloadtype.c	35	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\ortp\src\ortp.vcxproj]	EP_ortp	C:\Users\12\Desktop\linphone-desktop\submodules\ortp\src\port.c	94	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\ortp\src\ortp.vcxproj]	EP_ortp	C:\Users\12\Desktop\linphone-desktop\submodules\ortp\src\rtcp.c	373	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	C:\Users\12\Desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.cpp	32	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	C:\Users\12\Desktop\linphone-desktop\submodules\belcard\tester\belcard-vcard-tester.cpp	50	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	c:\users\12\desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.hpp	61	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	C:\Users\12\Desktop\linphone-desktop\submodules\belcard\tester\belcard-tester.cpp	32	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\belcard\tester\belcard_tester.vcxproj]	EP_belcard	C:\Users\12\Desktop\linphone-desktop\submodules\belcard\tester\belcard-vcard-tester.cpp	50	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	C2220	warning treated as error - no 'object' file generated [C:\Users\12\Desktop\linphone-desktop\WORK\desktop\Build\bellesip\src\bellesip.vcxproj]	EP_bellesip	c:\users\12\desktop\linphone-desktop\submodules\belle-sip\src\port.h	166	
Error	MSB6006	"cmd.exe" exited with code 1.	EP_ms2	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	
Error	MSB6006	"cmd.exe" exited with code 1.	EP_mswebrtc	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	
Error	MSB6006	"cmd.exe" exited with code 1.	EP_mswasapi	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	
Error	MSB6006	"cmd.exe" exited with code 1.	EP_linphone	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	
Error	MSB6006	"cmd.exe" exited with code 1.	EP_linphoneqt	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets	171	
`

**Comment by chowdarynamala** [comment]
I also see the same errors C2220 in belle-sip and linphone modules. 

Anyone please help in resolving these errors?

**Comment by S0U1SB4N3** [comment]
same build error types here please assist.
