### ISSUE TITLE
Clicking round button with a triangle inside crashes Linphone

### ISSUE THREAD

**Issue by ovari** [BelledonneCommunications/linphone-desktop#379]
Clicking round button with a triangle inside crashes Linphone. See the image below when the mouse pointer over the button which crashes Linphone if clicked.

![image](https://user-images.githubusercontent.com/17465872/83736526-1e7bf700-a695-11ea-844b-7d47f4b265d2.png)

Are you able to reproduce and fix?
Thank you

* [Linphone-4.2.0-alpha.63+59c4cc1.AppImage](https://www.linphone.org/snapshots/AppImages/Linphone-4.2.0-alpha.63+59c4cc1.AppImage)
* [Linux Mint 19.3 Cinnamon 64-bit](https://linuxmint.com/edition.php?id=274)
* No account has been configured

https://gitlab.linphone.org/BC/public/linphone-desktop/issues/25

**Comment by julonexus** [comment]
Do you have any trace or dump? Unfortunately, Logs didn't tell much.

**Comment by hubertbanas** [comment]
Seeing same behaviour with ```Linphone-4.2.0-alpha.95+ca4abd91.AppImage```

Looks like the crash is caused by libopus.so.0. Disabling opus doesn't help. 

```
[17:28:00:918][0xbc7b50][Info]app/App.cpp:770: "Open Linphone app."
[17:28:00:918][0xbc7b50][Info]app/App.cpp:224: "Creating subwindow: `qrc:/ui/views/App/Calls/CallsWindow.qml`."
[17:28:00:978][0xbc7b50][Info]app/App.cpp:231: "Subwindow status: `1`."
[17:28:00:983][0xbc7b50][Info]app/App.cpp:224: "Creating subwindow: `qrc:/ui/views/App/Settings/SettingsWindow.qml`."
[17:28:01:033][0xbc7b50][Info]app/App.cpp:231: "Subwindow status: `1`."
[New Thread 0x7fffbf7ab700 (LWP 26608)]
[17:28:01:470][0xbc7b50][Info]components/core/event-count-notifier/AbstractEventCountNotifier.cpp:66: "Notify event count: 0."
[New Thread 0x7fffbe2a9700 (LWP 26613)]
[New Thread 0x7fffbcf94700 (LWP 26614)]
[Thread 0x7fffbcf94700 (LWP 26614) exited]
[New Thread 0x7fffbcf94700 (LWP 26615)]
[Thread 0x7fffbcf94700 (LWP 26615) exited]
[New Thread 0x7fffbcf94700 (LWP 26616)]
[New Thread 0x7fffbb5fa700 (LWP 26617)]

Thread 14 "AppRun.wrapped" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7fffbb5fa700 (LWP 26617)]
0x00007fffef6339d2 in ?? () from /tmp/.mount_LinphoJil4Pk/usr/bin/../lib/libopus.so.0
(gdb) where
#0  0x00007fffef6339d2 in ?? () from /tmp/.mount_LinphoJil4Pk/usr/bin/../lib/libopus.so.0
#1  0x0000045100000000 in ?? ()
#2  0x00000000000003ea in ?? ()
#3  0x000003c000000000 in ?? ()
#4  0x00007fffbb5f7ce0 in ?? ()
#5  0x00000001fc000000 in ?? ()
#6  0x00000000000002b6 in ?? ()
#7  0x0000000000000000 in ?? ()
(gdb) list
1	../../../../../../linphone-sdk/mswebrtc/mswebrtc.c: No such file or directory.
(gdb) 
```

App also crashes when receiving a phone call (some info redacted with xxxx yyyy zzzz)

```
[17:35:44:561][0xbc7b50][Info]app/App.cpp:770: "Open Linphone app."
[17:35:44:561][0xbc7b50][Info]app/App.cpp:224: "Creating subwindow: `qrc:/ui/views/App/Calls/CallsWindow.qml`."
[17:35:44:609][0xbc7b50][Info]app/App.cpp:231: "Subwindow status: `1`."
[17:35:44:614][0xbc7b50][Info]app/App.cpp:224: "Creating subwindow: `qrc:/ui/views/App/Settings/SettingsWindow.qml`."
[17:35:44:657][0xbc7b50][Info]app/App.cpp:231: "Subwindow status: `1`."
[New Thread 0x7fffbf7ab700 (LWP 26840)]
[17:35:45:069][0xbc7b50][Info]components/core/event-count-notifier/AbstractEventCountNotifier.cpp:66: "Notify event count: 0."
[New Thread 0x7fffbdea1700 (LWP 26841)]
[17:35:52:413][0xbc7b50][Info]components/calls/CallsListModel.cpp:242: "Add call:" "<sip:yyyyy@xx.xx.xx.xx:xxxxx;transport=tls>" "\"First Last\" <sip:zzzzzzzzzz@xx.xx.xx.xx>"

Thread 10 "AppRun.wrapped" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7fffbdea1700 (LWP 26841)]
0x00007fffef6339d2 in ?? () from /tmp/.mount_LinphopSVskf/usr/bin/../lib/libopus.so.0
(gdb) where
#0  0x00007fffef6339d2 in ?? () from /tmp/.mount_LinphopSVskf/usr/bin/../lib/libopus.so.0
#1  0x0000045100000000 in ?? ()
#2  0x00000000000003ea in ?? ()
#3  0x000003c000000000 in ?? ()
#4  0x00007fffbde9ece0 in ?? ()
#5  0x00000001fc000000 in ?? ()
#6  0x00000000000002b6 in ?? ()
#7  0x0000000000000000 in ?? ()
(gdb) list
1	../../../../../../linphone-sdk/mswebrtc/mswebrtc.c: No such file or directory.
```

**Comment by ovari** [comment]
> Do you have any trace or dump? Unfortunately, Logs didn't tell much.

Can you please explicitly write in this issue instructions on how to get a trace or dump? Thank you

**Comment by julonexus** [comment]
@ovari You can start your app in gdb and do commands like @hubertbanas (where, list, bt) [check for example](http://www.yolinux.com/TUTORIALS/GDB-Commands.html)

@hubertbanas mswebrtc is used for the echo cancellation. Did you try to disable the option in settings?

**Comment by ovari** [comment]
Have just downloaded `Linphone-4.2.0-alpha.86+ef28ab01.AppImage`

Thanks for the link to `gdb` @julonexus. Can you please write at this issue:
1. Exactly what you want typed
2. Where the output will be

````
$ gdb Linphone-4.2.0-alpha.86+ef28ab01.AppImage
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from Linphone-4.2.0-alpha.86+ef28ab01.AppImage...(no debugging symbols found)...done.
(gdb) where
No stack.
(gdb) list
No symbol table is loaded.  Use the "file" command.
(gdb) 
````

**Comment by hubertbanas** [comment]
@julonexus 
In my case "Echo cancellation" has been disabled.

![linphone](https://user-images.githubusercontent.com/2602582/85007200-3178d780-b129-11ea-9d94-50d059aebfdc.png)

**Comment by julonexus** [comment]
@hubertbanas I'm sorry, I wrote a mistake. mswebrtc is used for echo cancellation but that and selected codecs are not taken account for this button. It will just play the ring sound. So it is the Player that crash when trying to play the file.
From @ovari's logs, it seems to be when pulseaudio is streaming(`Core:linphone: pulseaudio playback stream connected (48000Hz, 2ch)`) . I know that opus can crash if the system doesn't fully support it but maybe it is not this case.

**Comment by hubertbanas** [comment]
@julonexus do you have any suggestions or ideas to try out? I would really like to get to the bottom of it.

**Comment by julonexus** [comment]
Don't you have a backtrace?  The Appimage is build in RelWithDebInfo mode so you should get something with gdb.

First, you can open the file with a Player. I guess it should work but it's just in case ;)

The best could be by building from source and run it in Debug mode to see what happen.

**Comment by ovari** [comment]
> From @ovari's logs, it seems to be when pulseaudio is streaming(`Core:linphone: pulseaudio playback stream connected (48000Hz, 2ch)`) . I know that opus can crash if the system doesn't fully support it but maybe it is not this case.

How can a device be checked to see if it fully supports `opus`‽

Linux Mint Cinnamon shows the device has `2ch`. Sound works correctly when pressing either `Front Left` or `Front Right`.
![image](https://user-images.githubusercontent.com/17465872/85470441-64700f00-b5f2-11ea-864b-646e255708cc.png)

[Jami](https://jami.net/) works without crashing and [Jami](https://jami.net/) shows that it uses `opus 48000 Hz` audio codec.
![image](https://user-images.githubusercontent.com/17465872/85470563-91bcbd00-b5f2-11ea-94e4-0b4b0bd35e17.png)

Does the above indicate that `opus` is not the cause of this crash?

> The best could be by building from source and run it in Debug mode to see what happen.

Can you please:
1. Provide a link to a build from source;
2. Advise how to run it in Debug mode; and
3. Advise where the debug files are so they can be sent to you.

What do you think?

What else can be done to find and fix this bug?

Thank you

**Comment by julonexus** [comment]
I spotted a bug on concurrency in pulseaudio sources that I fixed on [alpha95](https://www.linphone.org/snapshots/AppImages/Linphone-4.2.0-alpha.95+3dd6b95b.AppImage)
Could you test it if it's resolve your issue?

**Comment by ovari** [comment]
> Could you test it if it resolves your issue?

Unfortunately [Linphone-4.2.0-alpha.95+3dd6b95b.AppImage](https://www.linphone.org/snapshots/AppImages/Linphone-4.2.0-alpha.95+3dd6b95b.AppImage) still crashes.

**Comment by hubertbanas** [comment]
FYI, Linphone-4.2.1.AppImage still crashes.

**Comment by julonexus** [comment]
./Linphone-4.2.1.AppImage --verbose with `gdb bt` still get nothing new?

**Comment by cs96and** [comment]
I am also having this problem on Debian 10 (buster).  The old flatpack version used to work OK for me, but it doesn't seem to be available any more.  The AppImage version keeps crashing with Illegal Instruction.

It looks like this problem, #391 and #392 are all related.  They all crash with "Illegal instruction".  This usually happens when a program is trying to use an SSE instruction that is not supported by the processor.

I have a AMD Phenom II X4 955 Processor, which only supports SSE, SSE 2 and SSE 3 (PNI).  It does not support SSSE3 or SSE 4.  Here are a list of the flags reported by cat /proc/cpuinfo

fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save

Is Linphone now being compiled with SSSE 3 or SSE 4 enabled?  Would it be possible to recompile with SSSE3 and SSE4 disabled please?

**Comment by julonexus** [comment]
The Appimage is build on a Debian9. It is not specify explicitly. The optimization is decided at the build time.
From the logs, Linphone is build with SSE, SSE2, SSE3, SSSE3, SSE4_1 and AVX enabled.

**Comment by cs96and** [comment]
> Linphone is build with SSE, SSE2, SSE3, SSSE3, SSE4_1 and AVX enabled.
That would explain why so many people are having a problem with it crashing.  Many people will be using older processors that do not support those instruction sets.

Would it be possible only enable SSE and SSE2 please?

**Comment by julonexus** [comment]
I don't know yet. Could build it on your hardware?

**Comment by julonexus** [comment]
@cs96and Opus is build with the RTCD (Runtime CPU detection). So even if it is build with SSSE3 support and you haven't it, Opus will not use it. So in theory, it shouldn't crash because of instruction sets.

**Comment by cs96and** [comment]
> @cs96and Opus is build with the RTCD (Runtime CPU detection). So even if it is build with SSSE3 support and you haven't it, Opus will not use it. So in theory, it shouldn't crash because of a difference in instruction sets.

I changed my ringtone to a .wav file, and clicking the play button no longer crashes the program.  However trying to call someone will still crash as soon as the remote phone starts ringing.

I ran the AppImage under GDB, and it is indeed calling AVX instructions (vxorps & vmovups).  This appears to be in libopus, so the runtime CPU detection cannot be working correctly...

```
Thread 1 "AppRun.wrapped" received signal SIGILL, Illegal instruction.
0x00007ffff0723900 in ?? () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libopus.so.0
(gdb) bt
#0  0x00007ffff0723900 in ?? () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libopus.so.0
#1  0x00007ffff071b2b2 in ?? () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libopus.so.0
#2  0x00007ffff0706a10 in opus_encoder_init () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libopus.so.0
#3  0x00007ffff0706c9a in opus_encoder_create () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libopus.so.0
#4  0x00007ffff6f0a047 in ?? () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libmediastreamer.so.11
#5  0x00007ffff6ecffac in ms_ticker_attach_multiple () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libmediastreamer.so.11
#6  0x00007ffff6ee9b49 in audio_stream_start_from_io () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libmediastreamer.so.11
#7  0x00007ffff7775546 in LinphonePrivate::MS2AudioStream::render(LinphonePrivate::OfferAnswerContext const&, LinphonePrivate::CallSession::State) ()
   from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/liblinphone.so.10
#8  0x00007ffff776cfcc in LinphonePrivate::StreamsGroup::render(LinphonePrivate::OfferAnswerContext const&, LinphonePrivate::CallSession::State) ()
   from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/liblinphone.so.10
#9  0x00007ffff775753c in LinphonePrivate::MediaSessionPrivate::updateStreams(SalMediaDescription*, LinphonePrivate::CallSession::State) ()
   from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/liblinphone.so.10
#10 0x00007ffff77597b1 in LinphonePrivate::MediaSessionPrivate::remoteRinging() () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/liblinphone.so.10
#11 0x00007ffff78c09a8 in ?? () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/liblinphone.so.10
#12 0x00007ffff77e83bd in LinphonePrivate::SalCallOp::processResponseCb(void*, belle_sip_response_event const*) ()
   from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/liblinphone.so.10
#13 0x00007ffff77fb121 in LinphonePrivate::Sal::processResponseEventCb(void*, belle_sip_response_event const*) ()
   from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/liblinphone.so.10
#14 0x00007ffff3f5da3f in belle_sip_client_transaction_notify_response () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libbellesip.so.1
#15 0x00007ffff3f5646a in belle_sip_provider_dispatch_message () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libbellesip.so.1
#16 0x00007ffff3f37275 in ?? () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libbellesip.so.1
#17 0x00007ffff3f355f7 in belle_sip_channel_process_data () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libbellesip.so.1
#18 0x00007ffff3f60242 in ?? () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libbellesip.so.1
#19 0x00007ffff3f2a315 in belle_sip_main_loop_run () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libbellesip.so.1
#20 0x00007ffff3f2a62f in belle_sip_main_loop_sleep () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libbellesip.so.1
#21 0x00007ffff78e313f in linphone_core_iterate () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/liblinphone.so.10
#22 0x00000000004f6fb3 in CoreManager::iterate() ()
#23 0x00007ffff4e2e6bb in QMetaObject::activate(QObject*, int, int, void**) () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libQt5Core.so.5
#24 0x00007ffff4e3b017 in QTimer::timeout(QTimer::QPrivateSignal) () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libQt5Core.so.5
#25 0x00007ffff4e3b308 in QTimer::timerEvent(QTimerEvent*) () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libQt5Core.so.5
#26 0x00007ffff4e2f28b in QObject::event(QEvent*) () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libQt5Core.so.5
#27 0x00007ffff58f0e7c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libQt5Widgets.so.5
#28 0x00007ffff58f7fd4 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libQt5Widgets.so.5
#29 0x00007ffff4e019d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libQt5Core.so.5
#30 0x00007ffff4e58d09 in QTimerInfoList::activateTimers() () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libQt5Core.so.5
#31 0x00007ffff4e594e9 in ?? () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libQt5Core.so.5
#32 0x00007fffece41f2e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007fffece421c8 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#34 0x00007fffece4225c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007ffff4e5982f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libQt5Core.so.5
#36 0x00007ffff4e0027a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libQt5Core.so.5
#37 0x00007ffff4e08ce0 in QCoreApplication::exec() () from /tmp/.mount_LinphoXexwjh/usr/bin/../lib/libQt5Core.so.5
#38 0x000000000047b52d in main ()
(gdb) disassemble 0x00007ffff0723900, +32
Dump of assembler code from 0x7ffff0723900 to 0x7ffff0723920:
=> 0x00007ffff0723900:  vxorps %ymm0,%ymm0,%ymm0
   0x00007ffff0723904:  vmovups %ymm0,0x4c(%rdi)
   0x00007ffff0723909:  vmovups %ymm0,0x40(%rdi)
   0x00007ffff072390e:  vmovups %ymm0,0x20(%rdi)
   0x00007ffff0723913:  vmovups %ymm0,(%rdi)
   0x00007ffff0723917:  movl   $0x32,0x5c(%rdi)
   0x00007ffff072391e:  movl   $0x19,0x60(%rdi)
End of assembler dump.
```

**Comment by julonexus** [comment]
I see... Thank you very much for your feedback

**Comment by fenugrec** [comment]
For me, on appimage  4.3.0.alpha.3 (running on core2 duo T9300), the crash is in libopus on opcode `vzeroupper`. For some reason the bt is not very nice on my build:

```
(gdb) bt
#0  0x00007ffff04279d2 in ?? () from /tmp/.mount_linphoo6F1J8/usr/bin/../lib/libopus.so.0
#1  0x0000045100000000 in ?? ()
#2  0x00000000000003ea in ?? ()
#3  0x000003c000000000 in ?? ()
#4  0x00007fffbeaface0 in ?? ()
#5  0x00000001fc000000 in ?? ()
#6  0x00000000000002b6 in ?? ()
#7  0x0000000000000000 in ?? ()
4: x/i $pc
=> 0x7ffff04279d2:	vzeroupper 

```
will try building from git if I have time

**Comment by julonexus** [comment]
Hello, could you test this [AppImage](https://www.linphone.org/snapshots/temp/Linphone-4.3.0-alpha.15+01ff927c.AppImage) please?

**Comment by hubertbanas** [comment]
> Hello, could you test this [AppImage](https://www.linphone.org/snapshots/temp/Linphone-4.3.0-alpha.15+01ff927c.AppImage) please?

This version no longer crashes here.

**Comment by fenugrec** [comment]
Also fixed here, thanks !

**Comment by ovari** [comment]
> Hello, could you test this [AppImage](https://www.linphone.org/snapshots/temp/Linphone-4.3.0-alpha.15+01ff927c.AppImage) please?

Fixed as no longer crashes and the sound is heard.

![image](https://user-images.githubusercontent.com/17465872/88133023-64c8ed80-cc24-11ea-8c2b-19249a6e056b.png)

Does this issue get closed now or do you wait until the released version of Linphone, say 4.3.1, is available?

Thank you

Linphone
Desktop 4.3.0-alpha-15-g01ff927c - Qt5.12.5
Core 4.5.0-alpha-39-g854fec7c5

Linux Mint 20 Cinnamon

**Comment by julonexus** [comment]
I'll close when the fix will be merged.
It will be available for the next release for sure.

**Comment by cs96and** [comment]
I still get a crash as soon as a call connects.  It looks like SSE 4.1 is still enabled...

```Thread 11 "AppRun.wrapped" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7fffbf7fe700 (LWP 5515)]
0x00007ffff06ff3c0 in opus_encode () from /tmp/.mount_LinphoDkjAjq/usr/bin/../lib/libopus.so.0
(gdb) bt
#0  0x00007ffff06ff3c0 in opus_encode () from /tmp/.mount_LinphoDkjAjq/usr/bin/../lib/libopus.so.0
#1  0x00007ffff6f003a8 in ?? () from /tmp/.mount_LinphoDkjAjq/usr/bin/../lib/libmediastreamer.so.11
#2  0x00007ffff6ec37e2 in ms_filter_process () from /tmp/.mount_LinphoDkjAjq/usr/bin/../lib/libmediastreamer.so.11
#3  0x00007ffff6ec683a in ?? () from /tmp/.mount_LinphoDkjAjq/usr/bin/../lib/libmediastreamer.so.11
#4  0x00007ffff6ec6882 in ?? () from /tmp/.mount_LinphoDkjAjq/usr/bin/../lib/libmediastreamer.so.11
#5  0x00007ffff6ec6882 in ?? () from /tmp/.mount_LinphoDkjAjq/usr/bin/../lib/libmediastreamer.so.11
#6  0x00007ffff6ec6882 in ?? () from /tmp/.mount_LinphoDkjAjq/usr/bin/../lib/libmediastreamer.so.11
#7  0x00007ffff6ec6882 in ?? () from /tmp/.mount_LinphoDkjAjq/usr/bin/../lib/libmediastreamer.so.11
#8  0x00007ffff6ec6882 in ?? () from /tmp/.mount_LinphoDkjAjq/usr/bin/../lib/libmediastreamer.so.11
#9  0x00007ffff6ec6882 in ?? () from /tmp/.mount_LinphoDkjAjq/usr/bin/../lib/libmediastreamer.so.11
#10 0x00007ffff6ec6882 in ?? () from /tmp/.mount_LinphoDkjAjq/usr/bin/../lib/libmediastreamer.so.11
#11 0x00007ffff6ec6882 in ?? () from /tmp/.mount_LinphoDkjAjq/usr/bin/../lib/libmediastreamer.so.11
#12 0x00007ffff6ec66a1 in ?? () from /tmp/.mount_LinphoDkjAjq/usr/bin/../lib/libmediastreamer.so.11
#13 0x00007ffff6ec64f0 in ?? () from /tmp/.mount_LinphoDkjAjq/usr/bin/../lib/libmediastreamer.so.11
#14 0x00007ffff0084fa3 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#15 0x00007ffff47694cf in clone () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) x/i $pc
=> 0x7ffff06ff3c0 <opus_encode+528>:    pmovsxwd -0x18(%rax),%xmm1
```

**Comment by julonexus** [comment]
@cs96and Would you mind to test [this version](https://www.linphone.org/snapshots/temp/Linphone-4.3.0-alpha.20+19b4c9cd.AppImage) please?

**Comment by cs96and** [comment]
Yes that's working now, thanks!

**Comment by julonexus** [comment]
Great. So, it was about the build of libopus.
There was no RTCD with AVX. It uses the compiler optimization with -mavx. But, for a reason that I ignore, gcc and clang have decided to put SSE as deprecated and prepend all SSE instructions with AVX instructions (even if -mno-sse2avx is specified).
So I reverted it if AVX optimizations are not presumed.
In addition, the 1.3.1 of libopus apply optimization on all codes. SSE4 optimization was applied to all code too, and not just some sources. So, I only do compiler optimization on source codes that support it. 

Thank you for your feedback.

**Comment by ovari** [comment]
https://www.linphone.org/releases/linux/app/Linphone-4.2.2.AppImage
