### ISSUE TITLE
Incorrect CallerID UTF8 russian language name encoding  

### ISSUE THREAD

**Issue by ssherge** [BelledonneCommunications/linphone-desktop#438]
When a call comes with UTF8 russian language encoded name it is displayed in wrong encoding.

![cnip](https://user-images.githubusercontent.com/72967338/96237617-9563bd80-0fae-11eb-8678-51d1fc2427d7.png)

![CallerID_Name](https://user-images.githubusercontent.com/72967338/96237683-a90f2400-0fae-11eb-8463-38ebaef635c9.png)

![ver](https://user-images.githubusercontent.com/72967338/96238421-80d3f500-0faf-11eb-91ca-8312c0288aa4.png)

Equally in ver. 4.2.2 and 4.2.3

**Comment by julonexus** [comment]
Please try with the nightly version : https://www.linphone.org/snapshots/windows/app/Linphone-4.3.0-alpha.26+52f5a9f0-win32.exe
If it works, you have to wait for 4.3 for a stable version.

**Comment by ssherge** [comment]
Thanks. But with alpha version unchanged. Same.

**Comment by julonexus** [comment]
Both versions are alpha? (caller and callee)

**Comment by ssherge** [comment]
CallerID information come from softswitch. The calling side is a hardware IP phone. I tested softphones Bria and PhonerLite under the same conditions. They display this information correctly.

**Comment by julonexus** [comment]
A fix has been merged on master. It will be available in the next nightly builds.

**Comment by Nikopol3000** [comment]
Please tell me if I understand correctly that the problem has not been solved yet? As in the stable release, the alpha is still not displayed in Cyrillic

**Comment by ssherge** [comment]
Hi all,I have tested in this version. Works correctly. 23.08.2021, 16:08, "Nikopol3000" ***@***.***>: Please tell me if I understand correctly that the problem has not been solved yet? As in the stable release, the alpha is still not displayed in Cyrillic—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
