### ISSUE TITLE
Contacs with german Umlaute are shown as ASCII after restart linphone

### ISSUE THREAD

**Issue by Jogile1** [BelledonneCommunications/linphone-desktop#495]
If you create a contact with one or more german Umlaute, then first all seems to be okay and will be shown correctly.
But, if you close linphone and start it again, these contacts are shown with ASCII Code instead of UTF-8 Characters, so e.g. Jürgen is shown as JÃ¼rgen.
In database friends.db the characterset is fine! It has to be a frontend bug.

**Comment by julonexus** [comment]
Hi, it has been resolved in snapshots version

**Comment by Jogile1** [comment]
Almost ;-)
The address fields, like e.g. street are not solved. Here you still see the ASCII signs instead of the UTF-8. All other fields are good in the latest snapshot.
Thx for your support!

**Comment by julonexus** [comment]
I confirm another bug : Data are not shown on restart after filling addresses with special characters
