### ISSUE TITLE
Blurry text on macOS

### ISSUE THREAD

**Issue by ddobrev** [BelledonneCommunications/linphone-desktop#60]
Note: this is a copy of the bug I've already sent to the mailing list at http://lists.nongnu.org/archive/html/linphone-users/2017-08/msg00021.html.

I have attached a screen-shot which clearly shows the Linphone client for macOS blurs the displayed text. I think this is a bug rather than a limitation of Qt because Qt has supported Retina displays since their introduction. I have seen the workaround with QT_AUTO_SCREEN_SCALE_FACTOR. I haven't tried it but even if it works, I find it too inconvenient to set it before using the app.
My friends and I consider switching from Skype but we use macOS and this bug puts strain on our eyes. What's more important, you know that most Mac users are particularly sensitive to irregularities in the UI and UX so I think a problem of such severity in this area would really slow down adoption of Linphone. Please fix this bug to both our and your benefit.

<img width="951" alt="blurry text" src="https://user-images.githubusercontent.com/5193072/29244515-874de768-7fc2-11e7-9683-157aedd87938.png">

**Comment by Wescoeur** [comment]
> What's more important, you know that most Mac users are particularly sensitive to irregularities in the UI

GNU/Linux and Windows users too. ;) I have fixed the font problem in this commit: e85464491dd0ccee381d1dcca3b7a7aa7d55ef74.

But, the high dpi scaling is not easily portable, you can see an other example here: https://bugreports.qt.io/browse/QTBUG-53022

**Comment by ddobrev** [comment]
@Wescoeur thank you very much. When can we expect a release with the fix?
By the way, https://stackoverflow.com/a/34465704 claims the macOS app also needs the <key>NSPrincipalClass</key>/<string>NSApplication</string> pair in Info.plist and I noticed your Info.plist lacks it. Please check and add it if it's required.

**Comment by Wescoeur** [comment]
You are right. Documented here: http://doc.qt.io/qt-5/highdpi.html#macos-and-ios
I fixed this, thanks you! A release is not planned for the moment, sorry. (I think within a maximum period of one month.)

**Comment by alanpearce** [comment]
This is still an issue, as there hasn't been a release since the commit  e854644. It's been quite a bit longer than one month; a release would be appreciated. It looks rather complicated to build as an outside user, unfortunately.
